# Site settings
title: Catherine Zhou
email: mail@catherinezhou.com
url: https://www.catherinezhou.com
description: "R enthusiast and Data Science Manager @Twitter"
repository: cattystats/cattystats.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#091109'
  links: '#d8ecd7'

# Footer settings
footer: Your Website

# "UA-NNNNNNNN-N"
google_analytics: UA-131311056-1

# resume pdf public link in google drive
google-drive-resume-file-id: 14tgGi85z1oxJJBBvLNhCNJV4oSzAvNc2

# Social networks usernames
social:
  - title: github
    url: https://github.com/cattystats
  - title: twitter
    url: https://twitter.com/catherinezh
  - title: linkedin
    url: https://www.linkedin.com/in/zhoucatherine/

talks:
  - title: "The Data Science of Learning"
    venue-publication: Towards Data Science Podcast 2020
    url: https://towardsdatascience.com/the-data-science-of-learning-e8a5a960f746 
  - title: "Why NYR? Finding You(R) Community"
    venue-publication: New York R Conference 2020 (same-day virtual impromptu talk)
    url: https://youtu.be/Fy9tMfjs9F8
  - title: "What Does a Data Scientist Do?"
    venue-publication: Codecademy News 2020
    url: https://news.codecademy.com/what-does-a-data-scientist-do/    
  - title: "Time Series, Two Ways: Anomaly Detection & Forecasting"
    venue-publication: New York Open Statistical Programming Meetup 2019
    url: https://youtu.be/n9GOvto69aQ
  - title: Building A Data Science Team From Scratch
    venue-publication: Big Data Spain 2018
    url: https://www.youtube.com/watch?v=4DJJNQTvVbs
  - title: Anomaly Detection With Time Series
    venue-publication: DC R Conference 2018
    url: https://www.youtube.com/watch?v=5nfe835TVcY
  - title: "Cracking The Data Science Interview: Learnings From Both Sides Of The Interview Table"
    venue-publication: New York rLadies 2018
    url: https://www.meetup.com/rladies-newyork/
  - title: "R Makes the World Go ‘Round: Data Driven Decision Making at JetBlue"
    venue-publication: New York R Conference 2017
    url: https://www.youtube.com/watch?v=5BnCMS109Ig
  

# Build settings
markdown: kramdown
permalink: pretty
