# Site settings
title: Catherine Zhou
email: mail@catherinezhou.com
url: https://www.catherinezhou.com
description: "R enthusiast and Data Scientist @Codecademy"
repository: cattystats/cattystats.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#091109'
  links: '#d8ecd7'

# Footer settings
footer: Your Website

# "UA-NNNNNNNN-N"
google_analytics: UA-131311056-1

# resume pdf public link in google drive
google-drive-resume-file-id: 165MY_vtHzlNmjImOMK1O2mGj797Y8Abu

# Social networks usernames
social:
  - title: github
    url: https://github.com/cattystats
  - title: twitter
    url: https://twitter.com/catherinezh
  - title: linkedin
    url: https://www.linkedin.com/in/zhoucatherine/
  - title: instagram
    url: https://www.instagram.com/cathzeta/

talks:
  - title: "Time Series, Two Ways: Anomaly Detection & Forecasting"
    venue-publication: New York Open Statistical Programming Meetup 2019
    url: https://github.com/cattystats/conference-talks/blob/master/nyhackr-2019/2019-NYR-Time-Series.pdf
  - title: Building A Data Science Team From Scratch
    venue-publication: Big Data Spain 2018
    url: https://www.youtube.com/watch?v=4DJJNQTvVbs
  - title: Anomaly Detection With Time Series
    venue-publication: DC R Conference 2018
    url: https://github.com/cattystats/Anomaly_Detection
  - title: "Cracking The Data Science Interview: Learnings From Both Sides Of The Interview Table"
    venue-publication: New York rLadies 2018
    url: https://www.meetup.com/rladies-newyork/?_cookie-check=ib69KpxlisKjf7id
  - title: "R Makes the World Go ‘Round: Data Driven Decision Making at JetBlue"
    venue-publication: New York R Conference 2017
    url: https://www.youtube.com/watch?v=5BnCMS109Ig
  

# Build settings
markdown: kramdown
permalink: pretty
